import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import LinkIcon from '@/assets/icons/link.svg?react';
import ShareIcon from '@/assets/icons/share.svg?react';
import useWebShare from '@/hooks/useWebShare';
import { DivideType } from '@domain/cobuying';
export default function InfoSection({ data }) {
    const { share } = useWebShare();
    const { type } = data;
    return (_jsxs(_Fragment, { children: [_jsxs("section", { className: "relative flex flex-col w-full pb-3 mb-4 ", children: [_jsx("p", { className: "text-caption text-default-500", children: data.ownerName }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("p", { className: "text-black text-h3-bold", children: data.productName }), _jsx(LinkIcon, {})] }), _jsx("div", { className: "mt-1", children: _jsx("p", { className: "text-caption text-default-600", children: `${data.deadline} 마감` }) }), _jsx("button", { className: "absolute right-0", onClick: () => share(`${data.productName} 공구해요`, `${data.productName} 공구해요`), children: _jsx(ShareIcon, {}) })] }), _jsx("p", { className: "text-caption text-default-600 mb-1.5", children: "\uAE30\uBCF8\uC815\uBCF4" }), _jsxs("section", { className: "flex flex-col gap-3 mb-7", children: [_jsxs("div", { className: "rounded-lg bg-zinc-50 flex flex-col p-2.5 gap-2.5", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("p", { className: "text-caption", children: "\uC0C1\uD488\uAC00\uACA9" }), _jsx("p", { className: "text-caption", children: `${data.totalPrice.toLocaleString()}원` })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("p", { className: "text-caption", children: "\uACF5\uAD6C\uAC00" }), _jsx("p", { className: "text-caption text-primary-400", children: `${type === DivideType.attendee
                                            ? data.perAttendeePrice.toLocaleString()
                                            : data.unitPrice.toLocaleString()}원` })] })] }), _jsxs("div", { className: "rounded-lg bg-zinc-50 flex flex-col p-2.5 gap-2.5", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("p", { className: "text-caption", children: "\uC0C1\uD488 \uC804\uCCB4\uC218\uB7C9" }), _jsx("p", { className: "text-caption", children: `${data.totalQuantity.toLocaleString()}개` })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("p", { className: "text-caption", children: type === DivideType.attendee ? '인 당 구매량' : '구매 가능 수량' }), _jsx("p", { className: "text-caption text-primary-400", children: `${type === DivideType.attendee
                                            ? (data.totalQuantity / data.targetAttendeeCount).toLocaleString()
                                            : data.remainQuantity.toLocaleString()}개` })] }), type === DivideType.attendee && (_jsxs("div", { className: "flex justify-between", children: [_jsx("p", { className: "text-caption", children: "\uBAA8\uC9D1 \uC778\uC6D0" }), _jsx("p", { className: "text-caption text-primary-400", children: `${data.attendeeCount.toLocaleString()} / ${data.targetAttendeeCount.toLocaleString()} 명` })] }))] })] }), _jsx("p", { className: "text-caption text-default-500 mb-1.5", children: "\uC548\uB0B4 \uBA54\uC2DC\uC9C0" }), _jsx("section", { className: "mb-7", children: _jsx("div", { className: "rounded-lg text-caption bg-zinc-50  p-2.5", children: data.memo }) })] }));
}
